const Map<String, String> en = {
  'txt_sign_up': 'sign up',
  'txt_login': 'login',
  'txt_by_continuing_you_agree': 'by continuing, you agree to Parallel',
  'txt_terms_conditions': 'terms & conditions',
  'txt_privacy_policy': 'privacy policy,',
  'txt_and': 'and',
  'txt_creating_profile': 'creating profile',
  'txt_please_enter_your_personal_information':
      'please enter your personal information to create a profile',
  'txt_name': 'name',
  'txt_write_your_name': 'write your name',
  'txt_email': 'email',
  'txt_write_your_email': 'write your email',
  'txt_password': 'password',
  'txt_create_a_password': 'create a password',
  'txt_password_must_contain_at':
      'password must contain at least 8 characters, 1 capital letter, 1 small letter and at least 1 number and special symbol.',
  'txt_repeat_password': 'repeat password',
  'txt_continue': 'Continue',
  'txt_already_have_an_account': 'already have an account',
  'txt_please_enter_code': 'Please enter the code we’ve sent to',
  'txt_6_digit_code': '6-digit code',
  'txt_enter_code': 'enter code',
  'txt_didnt_get_a_code': 'did\'t get a code?',
  'txt_resend_code': 'resend code',
  'txt_you_can_resend_the_code': 'you can send re-send the code only 3 times.',
  'txt_send_code': 'send code',
  'txt_you_have_only': 'you have only',
  'txt_attempts': 'attempts',
  'txt_answer_our_5_quick_question_to_complete':
      'answer our 5 quick questions to complete your profile',
  'txt_help_us_better_personalise_your_profile':
      'Help us better personalise your profile. This will help us better understand your needs and provide you with more relevant suggestions and recommendations',
  'txt_lets_start': 'let\'s start',
  'txt_maybe_later': 'maybe later',
  'txt_write_your_password': 'write your password',
  'txt_forgot_your_password': 'forgot your password?',
  'txt_dont_have_an_account': 'don’t have an account?',
  'txt_an_error_occurred': 'An error occurred!',
  'txt_feed': 'feed',
  'txt_chat': 'chat',
  'txt_notifications': 'notifications',
  'txt_profile': 'profile',
  'txt_save': 'save',
  'txt_create_a_new_password': 'create a new password',
  'txt_forgot_password': 'forgot password',
  'txt_confirmation_code': 'confirmation code',
  'txt_enter_an_email_connected_to_your_account':
      'enter an email, connected to your account. We will send you a confirmation code',
  'txt_you_have_successfully_reset': 'you have successfully reset your password!',
  'txt_confirmation_code_was_sent_to_your_email': 'confirmation code was sent to your email!',
  'txt_my_profile': 'my profile',
  'txt_followers': 'followers',
  'txt_following': 'following',
  'txt_create_post': 'create post',
  'txt_edit_profile': 'edit profile',
  'txt_about_me': 'about me',
  'txt_show_more': 'show more',
  'txt_posts': 'posts',
  'txt_gallery': 'gallery',
  'txt_your_profile_is_waiting_for_your_first_post':
      'your profile is waiting for your first post. What will you share with your followers?',
  'txt_here_will_be_displayed_media_that_you_used_in_posts':
      'here will be displayed media that you used in posts.',
  'txt_settings': 'settings',
  'txt_terms_privacy_policy': 'terms & privacy policy',
  'txt_support_email': 'support email',
  'txt_notification_settings': 'notification settings',
  'txt_1_personal_info': '1. Personal info',
  'txt_birthday_date': 'birthday date',
  'txt_yesterday': 'yesterday',
  'txt_today_at': 'today at',
  'txt_country': 'country',
  'txt_choose_your_country': 'choose your country',
  'txt_choose_your_birthday_date': 'choose your birthday date',
  'txt_choose': 'choose',
  'txt_2_about_you': '2. About you',
  'txt_fill_in_information_about_yourself':
      'Fill in information about yourself & your interests. This will help you find new friends and maybe even discover new opportunities.',
  'txt_my_interest': 'my interest',
  'txt_write_your_interest': 'write your interest',
  'txt_3_personalized_info': '3. Personalized info',
  'txt_customise_your_profile_by_filling_in_detailed_information':
      'Customise your profile by filling in detailed information. For example, your hobbies, education, skills, and so on. You can do this by clicking the \'Add new category\' button.',
  'txt_add_new_category': 'add new category',
  'txt_change_email': 'change email',
  'txt_change_password': 'change password',
  'txt_delete_profile': 'delete profile',
  'txt_write_something_about_yourself': 'write something about yourself',
  'txt_delete': 'delete',
  'txt_cancel': 'cancel',
  'txt_if_your_delete_this_page': 'if you delete this page, you won\'t be able to recover it',
  'txt_you_successfully_saved_changes': 'you successfully saved changes!',
  'txt_save_changes': 'save changes?',
  'txt_your_unsaved_changes_will_be_lost': 'your unsaved changes will be lost',
  'txt_dont_save': 'don\'t save',
  'txt_search': 'search',
  'txt_of': 'of',
  'txt_skip': 'skip',
  'txt_next': 'next',
  'txt_previous': 'previous',
  'txt_great_job': 'great job!',
  'txt_thank_you_for_helping_us': 'thank you for helping us better personalise your profile',
  'txt_lets_begin': 'let’s begin',
  'txt_category_new_name': 'add new category',
  'txt_category_name': 'category name',
  'txt_description': 'description',
  'txt_add_category': 'add category',
  'txt_your_current_email': 'your current email',
  'txt_new_email': 'new email',
  'txt_you_have_successfully_changed_your_email': 'you have successfully changed your email!',
  'txt_old_password': 'old password',
  'txt_new_password': 'new password',
  'txt_repeat_new_password': 'repeat new password',
  'txt_remove': 'remove',
  'txt_the_second_password_is_not_the_same_as_the_first':
      'The second password is not the same as the first. Try to enter again.',
  'txt_if_you_have_any_questions_issues':
      'If you have any questions, issues, or suggestions, please contact us for assistance. Please describe your problem in as much detail as possible, as this will help us to quickly understand the situation and provide you with an appropriate response. We will get back to you as soon as possible. Thank you!',
  'txt_topic': 'topic',
  'txt_write_your_topic': 'write your topic',
  'txt_write_description': 'write description',
  'txt_send_mail': 'send mail',
  'txt_media': 'media',
  'txt_post': 'post',
  'txt_publish_post': 'publish post',
  'txt_write_your_text_here': 'write your text here',
  'txt_add': 'add',
  'txt_nft': 'nft',
  'txt_add_nft_link': 'add nft link',
  'txt_upload_photo': 'upload photo',
  'txt_upload_video': 'upload video',
  'txt_you_successfully_published_post': 'You successfully published post!',
  'txt_youtube': 'youtube',
  'txt_likes': 'likes',
  'txt_comments': 'comments',
  'txt_completed': 'completed',
  'txt_processing': 'processing',
  'txt_paused': 'paused',
  'txt_requests': 'requests',
  'txt_alerts': 'alerts',
  'txt_to_ensure_better_results_kindly_provide_a_more':
      'to ensure better results, kindly provide a more detailed description of what you\'re looking for.',
  'txt_please_write_your_desire': 'please, write your desire',
  'txt_minimum_50_symbols': 'Minimum 50 symbols',
  'txt_smart_desires': 'smart desires',
  'txt_results': 'results',
  'txt_pause_searching': 'pause searching',
  'txt_it_may_take_some_time':
      'It may take some time, but don\'t worry! You will receive a notification once your request has been processed.',
  'txt_here_you_will_find_a_list_of_all_your_completed_searches':
      'here you will find a list of all your completed searches',
  'txt_here_you_will_find_a_list_of_all_your_process_searches':
      'here you will find a list of all your in process searches',
  'txt_here_you_will_find_a_list_of_all_your_searches_that_are_currently_paused':
      'here you\'ll find a list of all your searches that are currently paused',
  'txt_your_search_is_currently_on_hold':
      'Your search is currently on hold. You have the flexibility to pick it up again whenever you\'re ready.',
  'txt_resume_searching': 'resume searching',
  'txt_if_you_delete_this_search': 'if you delete this search, you will not be able to recover it.',
  'txt_follow': 'follow',
  'txt_unfollow': 'unfollow',
  'txt_send_message': 'send message',
  'txt_user_profile': 'user profile',
  'txt_log_out': 'log out',
  'txt_here_you_will_find_the_results_of_your_search':
      'here you will find the results of your search',
  'txt_user_not_found_or_does_not_exist':
      'The user you are looking for is not found or does not exist',
  'txt_add_youtube_link': 'add youtube link',
  'txt_edit_your_image': 'edit your image',
  'txt_enter_valid_email': 'enter valid email',
  'txt_photos': 'photos',
  'txt_videos': 'videos',
  'txt_are_you_sure_want_to_log_out': 'are you sure you want to log out',
  'txt_edit_post': 'edit post',
  'txt_delete_post': 'delete post',
  'txt_here_will_be_displayed_all_notifications': 'Here will be displayed all notifications.',
  'txt_here_you_can_see_all_users_who_will_follow_you':
      'Here you can see all users who will follow you.',
  'txt_when_you_begin_following_someone_they_will_be_displayed_here':
      'When you begin following someone, they will be displayed here.',
  'txt_block_user': 'block user',
  'txt_report_user': 'report user',
  'txt_user_wont_be_able_to_message_you_or_view':
      'User won’t be able to message you or view the information about you',
  'txt_the_user_is_blocked': 'the user is blocked!',
  'txt_write_report_topic': 'write report topic',
  'txt_write_report_description': 'write report description',
  'txt_send_report': 'send report',
  'txt_your_user_report_has_been_sent' : 'your user report has been sent!',
  'txt_report_post' : 'report post'
};
